version: "3.3"

services:
  app:
    build:
      context: ../code/server
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
